name: macOS workflow

on:
  push:
    branches: [ trunk ]
  workflow_dispatch:

jobs:
  build:
    name: Build macOS dmg
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          set -x
          #brew install pkg-config autoconf automake libxml2 sdl sdl_image sdl2 sdl2_image sdl2_mixer protobuf-c glew boost ftgl dylibbundler create-dmg 
          # for 0.2.X
          brew install sdl sdl_image dylibbundler create-dmg 
          # for 0.4
          #brew install sdl2 sdl2_image sdl2_mixer protobuf-c glew boost ftgl dylibbundler create-dmg 
          # git clone https://gitlab.com/zmanuel/armagetronad.git
          # git -C armagetronad checkout legacy_0.2.8.3_macos_bundle
          # import build settings
          . ./INFO
          wget "${TARBALL}" -O source.tbz
          (mkdir source; cd source; tar -xjf ../source.tbz; mv * ../armagetronad)
          rmdir source source.tbz
          # (cd armagetronad && ./bootstrap.sh)
          mkdir client
          export ARMAGETRONAD_FAKERELEASE=true
          (cd client && ../armagetronad/configure --disable-sysinstall --disable-etc --prefix=/usr && make -j `nproc`)
          (cd client && bash src/macosx/build_bundle.sh `pwd`/../release) 
          #mkdir server
          #(cd server && ../armagetronad/configure --disable-sysinstall --disable-etc --prefix=/usr --disable-glout && make -j `nproc`)
          #(cd server && bash src/macosx/build_bundle.sh `pwd`/../release)
          set +x
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macOS images
          path: release
      - name: SSH Agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_DEPLOY }}
      - name: Deploy
        run: |
          rsync release ${UPLOAD}
